CREATE TABLE [dbo].[Addresses]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[City] VARCHAR(24) NOT NULL,
	[State] VARCHAR(24) NOT NULL,
	[StreetAddress] VARCHAR(24) NOT NULL,
	[PostalCode] VARCHAR(24) NOT NULL,
	[CountryId] INT FOREIGN KEY REFERENCES Countries(Id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
	[UserId] INT FOREIGN KEY REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)
