CREATE TABLE [dbo].[Conversations]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(24),
	[LastMessageId] BIGINT FOREIGN KEY REFERENCES [dbo].[Messages](Id) ON UPDATE CASCADE ON DELETE CASCADE
)
