CREATE TABLE [dbo].[ItemOptions]
(
	[ItemId] INT NOT NULL FOREIGN KEY REFERENCES [Items](Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[OptionId] INT NOT NULL FOREIGN KEY REFERENCES [Options](Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (ItemId,OptionId)
)
