CREATE TABLE [dbo].[Items]
(
	[Id] INT NOT NULL PRIMARY KEY	IDENTITY,
	[Quantity] INT NOT NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[ImgUrl] VARCHAR(255) NOT NULL,
	[Views] INT,
	[ProductId] INT NOT NULL FOREIGN KEY REFERENCES Products(Id) ON UPDATE CASCADE ON DELETE CASCADE
)
