CREATE TABLE [dbo].[OrderItems]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[OrderId] INT NOT NULL FOREIGN KEY REFERENCES Orders(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[ItemId] INT NOT NULL FOREIGN KEY REFERENCES Items(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[Price] DECIMAL(10,2) NOT NULL,
	[Quantity] INT NOT NULL,
	UNIQUE(OrderId,ItemId)
)
