CREATE TABLE [dbo].[Orders]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[TimeStamp] DATETIME2(0) NOT NULL,
	[Status] INT NOT NULL,
	[Total] DECIMAL(18,2) NOT NULL,
	[SessionId] VARCHAR(255),
	[PaymentIntentId] VARCHAR(255),
	[AddressId] INT NOT NULL FOREIGN KEY REFERENCES Addresses(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE
)
