CREATE TABLE [dbo].[ProductDiscounts]
(
	[ProductId] INT NOT NULL FOREIGN KEY REFERENCES Products(Id) ON UPDATE CASCADE ON DELETE CASCADE,
    [DiscountId] INT NOT NULL FOREIGN KEY REFERENCES Discounts(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(ProductId,DiscountId)
)
