CREATE TABLE [dbo].[Products]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(24) NOT NULL,
	[Description] TEXT NOT NULL,
	[CategoryId] INT NOT NULL FOREIGN KEY REFERENCES Categories(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[DiscountId] INT FOREIGN KEY REFERENCES Discounts(Id) ON UPDATE CASCADE ON DELETE SET NULL
)
