CREATE TABLE [dbo].[Reviews]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Comment] VARCHAR(450) NOT NULL,
	[UserId] INT FOREIGN KEY REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[ItemId] INT FOREIGN KEY REFERENCES Items(Id) ON UPDATE CASCADE ON DELETE CASCADE
)
