CREATE TABLE [dbo].[Tokens]
(	
    [Value] VARCHAR(255) PRIMARY KEY,
	[Purpose] INT NOT NULL,
	[ValidTill] DATETIME2(0) NOT NULL,
	[UserId] INT FOREIGN KEY REFERENCES [Users](Id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
)
