CREATE TABLE [dbo].[UserLogins]
(
	[ProviderKey] VARCHAR(450) NOT NULL,
	[LoginName] VARCHAR(450) NOT NULL,
	[UserId] INT NOT NULL FOREIGN KEY REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY(ProviderKey,LoginName)
)
