CREATE TABLE [dbo].[UserRoles]
(
	[UserId] INT FOREIGN KEY REFERENCES [Users](Id) ON UPDATE CASCADE ON DELETE CASCADE,
	[RoleId] INT FOREIGN KEY REFERENCES [Roles](Id) ON UPDATE CASCADE ON DELETE CASCADE,
	PRIMARY KEY (UserId,RoleId)
)
